### PR TITLE
Next step in git is to review PRs! Here are a few suggestions.

### PR DESCRIPTION
**Pull request by srz2**
Hi @WadieBenabdouh,

First off, _congrats_ on getting started with GitHub! I saw your post on reddit and I wanted to introduce you to the next step in github which is collaboration.

I wanted to make a couple suggestions. You are free to either accept them or reject them, I wont care either way. But I was bored and I wanted to help out.

Stay inspired and code on!

Happy Coding :)

### CODE REVIEW

**Comment by srz2** [comment]
To Add because i realize it may not come across in my commit messages to a newbie, I did the following:

1. Renamed your command filename
   I did this because you really want to stay away from spaces in file names, especially in program/script files. It becomes hard or confusing especially running the commands in a command line interface like CMD

2. Added a header to the command filename
   I would highly recommend that you add basic headers (commented text) to your script files to describe what they do. As you do more complicated things, you will thank yourself. I normally include: What the script does, the date it was created, who originally authored it, and any accepted arguments

3. Changed formatting to the README file
   I thought this could be neatend up a little. Capitalized a couple things thing what not.

**Comment by WadieBenabdouh** [comment]
@srz2 man that's really kind of you to add some improvements to my first post, thank you so much and I appreciate your help.
Now I learned some new tips from you!

**Review by WadieBenabdouh — APPROVED** [review]

**Review by WadieBenabdouh — APPROVED** [review]

**Comment by srz2** [comment]
For the record, if you wanted my changes in your repo, you have to actually merge them in via github, not just approve them.

**Review by WadieBenabdouh — APPROVED** [review]

**Comment by WadieBenabdouh** [comment]
Thanks dude!

**Pull request closed without merging**
